### ISSUE TITLE
Not able to send multiple files

### ISSUE THREAD

**Issue by andreaslutsch** [cubiclesoft/php-discord-sdk#2]
Hello, I am using the sdk to send an embed object with file attachments through a webhook.
From the example one file can be sent by passing the array for the fileinfo like this

```php
"fileinfo" => array(
                    "name" => "file",
                    "filename" => 'avatar.jpg',
                    "type" => "image/jpeg",
                    "data" => file_get_contents($avatar_path)
                )
```
But how would one send multiple files to attach for the multiple elements of the embed like the author avatar, thumbnail and footer icon?

Passing an array with an array for each file or extending the array with the four required values doesn't seem to work like this

```php
"fileinfo" => array(
                array(
                    "name" => "file",
                    "filename" => 'thumbnail.jpg',
                    "type" => "image/jpeg",
                    "data" => file_get_contents($avatar_path)
                ),
                array(
                    "name" => "file",
                    "filename" => 'avatar.jpg',
                    "type" => "image/jpeg",
                    "data" => file_get_contents($avatar_path)
                )
            ), 
```

In `http.php`  from line 1057 to 1083 is there only I understand that files array gets shifted to get multiple files and send them.

**Comment by andreaslutsch** [comment]
I changed the line 1693 in http.php from
```php
foreach ($options["files"] as $num => $info)
```
to
```php
foreach ($options["files"][0] as $num => $info)
```
in order to iterate through the arrays and read each array of the files from the second block of code in the first comment.

It seems that the images are being read now, but only the first in the array is being sent to the discord embed.
<img width="540" alt="WindowsTerminal 2021-03-29-18-06 2426" src="https://user-images.githubusercontent.com/7101531/112865973-98b0b880-90b9-11eb-8f2a-9689e51b28c0.png">

**Comment by cubiclesoft** [comment]
Modifying [Ultimate Web Scraper Toolkit](https://github.com/cubiclesoft/ultimate-web-scraper) core is not recommended.

I've updated the Discord SDK.  Give it a try.
