### ISSUE TITLE
$postvars not passed when PATCHing

### ISSUE THREAD

**Issue by gabrc52** [cubiclesoft/php-discord-sdk#4]
An example of a command or API call that needs a PATCH command is setting nicknames:

```php
$discord->RunAPI("PATCH", "guilds/$server/members/$id", array("nick"=>$name), array(), 204);
```

I got it to properly work by changing line 67 of sdk_discord.php to 

```php
if ($method === "POST" || $method === "PUT" || $method === "PATCH")
```

I could make it into a pull request but I'm not sure what the other implications are.

Is there a reason you're only passing the variables with specific methods? (I haven't dived too much into Discord API). Otherwise having general code that does the same thing for all methods would be good.

**Comment by cubiclesoft** [comment]
Fixed.

Mostly done that way because HTTP verbs are largely inconsistent in general.
